### ISSUE TITLE
Cloud Workflow

### ISSUE THREAD

**Issue by singulart** [GoogleCloudPlatform/workflows-demos#57]
Hi Team!

A client of mine considers Cloud Workflow for one of its products. As a solution architect, I've been tasked with this assessment exercise. Following the beautifully done "Pic-a-daily" workshop https://codelabs.developers.google.com/codelabs/cloud-picadaily-lab5, there are still a few topics that require clarification.
1. Can business users make changes to Cloud Workflows?

The impression I've got from the Pic-a-daily workshop is that putting together the workflow definition requires the technical expertise (passing state between steps, setting up error handling, retries, authN, authZ etc.) Does Cloud Workflow out-of-the-box functionality allow extracting the orchestration logic out, so that it can be manipulated by business users with little or no technical background? Think If-This-Then-That no-code approach.
2. How do OAuth2 and OIDC settings are applied in runtime?

The workflow definition [example](https://github.com/GoogleCloudPlatform/serverless-photosharing-workshop/blob/master/workflows/workflows.yaml#L40).
3. URLs as Workflow args

[Workflow definition](https://github.com/GoogleCloudPlatform/serverless-photosharing-workshop/blob/master/workflows/workflows.yaml#L23) used in the workshop defines URLs of orchestrated endpoints as args. For external APIs (Google Vision in our case) this is fine, but for internal services this may be an issue. For instance COLLAGE_URL points to the following Cloud Function URL: https://collage-service-xgstcqnrla-ew.a.run.app/. Was wondering if this is the only way the workflow runtime can do the orchestration job? Or, it's also possible to hide the specific service behind an API gateway?

That's all I wanted to clarify for now :) Thanks in advance!

**Comment by meteatamel** [comment]
Hi @singulart,

1. You're right. Currently, you need to be technical to be able to figure out the YAML syntax and construct it yourself. We're thinking of ways to make this more visual and less technical in the future.

2. When you specify OAuth2/OIDC, Workflows authenticates as its associated service account. Please take a look at [this](https://cloud.google.com/workflows/docs/authenticate-from-workflow) doc page for more details.

3. We passed in URLs as runtime arguments because each URL of a service will be unique for each project. We didn't want to hardcode URLs (that will be specific to our project) or ask people to replace some placeholder URLs with real URLs from their project. It's up to you how you want to handle this. You can certainly use an API gateway URL instead, as long as that URL is accessible from Google Cloud / Workflows.

Hope this is useful.

**Comment by meteatamel** [comment]
Please re-open if you have further questions.
