### ISSUE TITLE
Create a sample for event-triggered Cloud Run Jobs leveraging execution override

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/workflows-demos#99]
We need a YAML sample and instructions to set up a Workflow that executes a Cloud Run job, passing  the events payload as environment variables via Execution overrides.

**Comment by meteatamel** [comment]
Hi @steren, there's already an Eventarc+Workflows+CloudRun jobs tutorial and sample.

Tutorial: https://cloud.google.com/workflows/docs/tutorials/execute-cloud-run-jobs

Sample: 
Workflows piece: https://github.com/GoogleCloudPlatform/workflows-demos/blob/master/cloud-run-jobs/workflow.yaml
Cloud Run jobs piece: https://github.com/GoogleCloudPlatform/jobs-demos/blob/main/parallel-processing/process.py

Are you suggesting to update this tutorial/sample to use execution overrides or are you suggesting a new sample/tutorial? 

Assuming it's the former, the sample currently has the bucket and file name hardcoded. Are you suggesting to update it so that the bucket name and file name are passed from event to Workflows to Cloud Run jobs as env variables execution overrides?

Note: I don't own these 2 samples, did/should we check with the sample owners first?

**Comment by steren** [comment]
yes, update this tutorial to pass the event attributes as overrides in the execution of the job, and make sure the jonb container is reading these values instead of using hardcoded balues

**Comment by meteatamel** [comment]
@steren, Ok, I'll look into this and update here once I have something.

**Comment by meteatamel** [comment]
@steren, mind approving the pull request on the Cloud Run jobs repo? https://github.com/GoogleCloudPlatform/jobs-demos/pull/39

**Comment by meteatamel** [comment]
Sample updated in both repos. I'll open a separate bug doc for the tutorial.
